### ISSUE TITLE
Error when retrieving an OPT with template_id containing special characters

### ISSUE THREAD

**Issue by ricardofago** [ehrbase/ehrbase#23] opened 2019-10-28 18:34 UTC
I did ``POST (...)/template/adl1.4`` with a few local OPTs and they are properly listed on ``GET (...)/template/adl1.4``, but it seems I cannot retrieve it using the ``GET (...)/template/adl1.4/{{templateId}}`` endpoint if ``template_id`` has special characters, ending up with a ``400 Bad Request`` response status instead. The problem goes away if I remove characters such as accented letters.

This is possibly due to URL encoding/escaping (specially when using two bytes instead of one, in my scenario, because ``template_id`` comes from an external source and is expressed in Brazilian Portuguese).

I tried it running v0.9.0 from the master branch, using an OPT file used in Brazil.

**Comment by jakesmolka** [comment] 2019-11-15 10:43
Hey @ricardofago and thanks for the feedback! I've tried to reproduce the issue but wasn't successful. Here's what I did:

- Modified an OPT file I regularly use so that it's template ID is `dâblioTemplate` (just a quick example)
- POSTed it, cross-checked if this was successful with GETting the template list from the server
- GETting it specifically with the request `http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4/d%C3%A2blioTemplate`

I encountered no problems doing that. 

However, when using an unencoded request like `http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4/dâblioTemplate` I get a `400 Bad Request`, too. 
So would you example work when encoding the parameter?

From my perspective this encoding should happen on the client side, so I wouldn't count that as bug. But I'll discuss that with the team and post an update about the decision.

**Comment by jakesmolka** [comment] 2019-11-18 14:03
Hey again @ricardofago. So as far as we understood the problem, and with given standards [1], we decided this behavior is as intended.

I'll close this issue but feel free to reopen it or open another one if the problem persists.

[1] For instance https://tools.ietf.org/html/rfc3986#section-2 and how Spring MVC internals handle REST parameter encoding

**Closed by jakesmolka** 2019-11-18 14:03 UTC
