### ISSUE TITLE
Error in Robot: Alternative flow 1: get CONTRIBUTIONS of existing EHR with no CONTRIBUTIONS

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#601] opened 2021-09-24 00:51 UTC
## Test Case/s To Reproduce Issue

```
# path to test case
tests/robot/CONTRIBUTION_TESTS/LIST_CONTRIBUTIONS
```

```
# robot command to execute related test case(s) in your terminal/console

robot -v nodocker -d results -L TRACE robot/CONTRIBUTION_TESTS/

# Valid test suite folder names

CONTRIBUTION_TESTS
```

## Actual Result

`There is an error in this test: Variable '${versions}' not found. Did you mean: ${VERSION}`

**Comment by wlad** [comment] 2021-10-04 14:44
@ppazos do you still have an issue with this? If so feel free to reopen.

For me it works, can't reproduce the issue, so I'll close it for now.

**Closed by wlad** 2021-10-04 14:44 UTC
Labels: bug

**Comment by ppazos** [comment] 2021-10-05 22:19
@wlad I have updated ehrbase, I don't see the error any more.
