### ISSUE TITLE
24 Hour Average /width : The value 0 must be equal to 24

### ISSUE THREAD

**Issue by ATHULKNAIR** [ehrbase/ehrbase#775] opened 2022-03-21 17:00 UTC
## Configuration information

- EHRbase version: 0.20.0-SNAPSHOT
- openEHR_SDK version: 1.18.0-SNAPSHOT
- Archie version: 1.0.4
- PostgreSQL version: PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc, a 7faa5e1be7 p b4de6ea762, 64-bit
- Java Runtime version: Oracle Corporation 11.0.14.1+1
- Operating System version: Linux amd64 5.10.0-0.bpo.9-amd64

## Steps to reproduce ## 

I have attached the OPT file and the composition i posted to EHRbase used in getting the error  :

OPT file : [opt.txt](https://github.com/ehrbase/ehrbase/files/8317469/opt.txt)
Composition : 
{
    "a1/category|code": "433",
    "a1/category|value": "event",
    "a1/category|terminology": "openehr",
    "a1/context/start_time": "2022-03-21T14:32:36.282Z",
    "a1/context/setting|code": "238",
    "a1/context/setting|value": "other care",
    "a1/context/setting|terminology": "openehr",
    "a1/blood_pressure/any_event:0/systolic|unit": "mm[Hg]",
    "a1/blood_pressure/any_event:0/systolic|magnitude": 71,
    "a1/blood_pressure/any_event:0/diastolic|unit": "mm[Hg]",
    "a1/blood_pressure/any_event:0/diastolic|magnitude": 57,
    "a1/blood_pressure/any_event:0/position|code": "at1002",
    "a1/blood_pressure/any_event:0/position|value": "Reclining",
    "a1/blood_pressure/any_event:0/position|terminology": "local",
    "a1/blood_pressure/any_event:0/time": "2022-03-21T14:32:36.282Z",
    "a1/blood_pressure/a24_hour_average/systolic|unit": "mm[Hg]",
    "a1/blood_pressure/a24_hour_average/systolic|magnitude": 4,
    "a1/blood_pressure/a24_hour_average/diastolic|unit": "mm[Hg]",
    "a1/blood_pressure/a24_hour_average/diastolic|magnitude": 2,
    "a1/blood_pressure/a24_hour_average/math_function|code": "146",
    "a1/blood_pressure/a24_hour_average/math_function|value": "mean",
    "a1/blood_pressure/a24_hour_average/math_function|terminology": "openehr",
    "a1/blood_pressure/a24_hour_average/width": "PT2H",
    "a1/blood_pressure/a24_hour_average/time": "2022-03-21T14:32:36.282Z",
    "a1/blood_pressure/language|code": "en",
    "a1/blood_pressure/language|terminology": "ISO_639-1",
    "a1/blood_pressure/encoding|code": "UTF-8",
    "a1/blood_pressure/encoding|terminology": "IANA_character-sets",
    "a1/composer|name": "Medblocks UI",
    "a1/language|code": "en",
    "a1/language|terminology": "ISO_639-1",
    "a1/territory|code": "IN",
    "a1/territory|terminology": "ISO_3166-1"
  }

POST this composition to EHRbase api.

## Actual result ##

{
	"error": "Bad Request",
	"message": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at1042]/width: The value 0 must be 
         equal to 24"
}

## Expected result (Acceptance Criteria) ##

204 Created.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment] 2022-03-22 11:25
Validated on dev.

Also dos not work with
"a1/blood_pressure/a24_hour_average/width": "PT24H",

I think the Problem is that 24 H is converted to 1 D

Internal issue CDR-312

**Comment by stefanspiska** [comment] 2022-03-29 18:58
fixed in https://github.com/ehrbase/openEHR_SDK/pull/346

**Closed by stefanspiska** 2022-03-29 18:58 UTC
Labels: bug
