### ISSUE TITLE
Unexpected result in AQL query when two elements in same cluster>1 are fetched in the where clause

### ISSUE THREAD

**Issue by rtchaya** [ehrbase/ehrbase#1013] opened 2022-12-06 05:08 UTC
## Configuration information

EHRbase version:0.21.1
openEHR_SDK version:1.19.0
Archie version:2.0.1
PostgreSQL version:PostgreSQL 13.7, compiled by Visual C++ build 1914, 64-bit
Java Runtime version:Oracle Corporation 18.0.2+9-61

## Steps to reproduce ## 
The composition has composition > 1 CLUSTER (cardinality 0..*)
AQL query with where clause saying fetch the composition that contains a cluster with criteria 1 and also contains cluster with criteria2 (foo2)
If a composition has two clusters, each satisfying one criteria, It is selecting the composition which is unexpected.

eg:

Using Symptom/sign screening questionnaire cluster archetype  Specific symptom/sign as 0…*.
I have inserted 3 clusters with Symptom or sign name and Presence?

0th element has
Symptom or sign name = Depression
Presence = No

1st element has
Symptom or sign name = Anxiety
Presence = No

2nd element has
Symptom or sign name = Feeding/eating
Presence = Yes

Below is the AQl to retrieve all records with criteria1 as Symptom or sign name = Depression and criteria 2 as Presence = Yes.
But the AQl results is not as expetected

``` json5
{ "q" : "SELECT \
    e/ehr_id/value as ehrid, c/uid/value as compid, \
    o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value as Condition, \
    o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value as Result \
  FROM ehr e \
  CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] \
  CONTAINS (observation o[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]) \
  WHERE o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value = 'Depression' \
    and o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value = 'Yes' \
    and c/archetype_details/template_id/value='sample_questionnaire.en.v0'" }
```

Attached is the sample-questionnaire.en.v0.opt file along with the sample composition and aql and the sample composition
[sample_questionnaire.en.v0.zip](https://github.com/ehrbase/ehrbase/files/10162806/sample_questionnaire.en.v0.zip)

The AQl is supposed to retrieve all records with Symptom or sign name = Depression and Presence = Yes.

## Actual result ##

Note that the composition has only
e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1
"Anxiety",
"No"
"Depression",
"No"
"Feeding/eating",
"Yes"
 But the AQl is returning the composition although cluster 1 has met  criteria 1  (Depression) and cluster 2 has met criteria 2(Yes ). 

## Expected result (Acceptance Criteria) ##
The expected was it should satisfy both the criteria within the same cluster.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment] 2022-12-06 12:12
Please try this with v0.22.0

**Comment by rtchaya** [comment] 2022-12-14 14:42
Please note, I tested this on v0.22.0 but still not getting the expected result

**Comment by vladislavploaia** [comment] 2022-12-26 10:33
Hello @rtchaya ,
Thank you for this ticket.
I was trying to reproduce it, but blocked at composition submission.
Could you please provide composition content in FLAT format or in XML, so I can commit it and check your AQL statement?
Thanks in advance.
CC: @vidi42

**Comment by rtchaya** [comment] 2023-01-16 09:28
Hi @vladislavploaia 

Please find attached the flat json.

Sorry for the delay.
[sample_questionnaire-flatjson.txt](https://github.com/ehrbase/ehrbase/files/10424339/sample_questionnaire-flatjson.txt)

**Comment by rtchaya** [comment] 2023-01-16 11:37
Hi @vladislavploaia 
This is in a way related to cartesian product issue mentioned in

https://github.com/ehrbase/ehrbase/issues/833

We see this issue in almost all templates where we are using cardinality 0..*. 
In these templates we cant give the named/value path as suggested in #833 as the path is same for all cardinalities.

Any workaround/fix  for this issue is greatly appreciated.

**Comment by vladislavploaia** [comment] 2023-01-16 12:09
Hello @rtchaya ,
Used your latest composition (in FLAT format) and was not able to reproduce your issue.
Right now, seems to be fine. Please check and let me know.
After your confirmation, I will close this ticket.
![image](https://user-images.githubusercontent.com/100927963/212674693-f2f9496b-f76f-4093-81b5-9ff13b98dac8.png)
Tested on below versions:
- EHRbase version: 0.24.0-SNAPSHOT
- openEHR_SDK version: 1.24.0-SNAPSHOT

**Comment by rtchaya** [comment] 2023-01-16 13:38
@vladislavploaia  
Sure, will check and get back.

Thanks

**Comment by rtchaya** [comment] 2023-01-19 07:08
@vladislavploaia 
scenario:
composition 1 with 
"Anxiety": "No"
"Depression": "No"
"Feeding/eating": "Yes" 

composition 2 with 
"Anxiety": "No"
"Depression": "Yes"
"Feeding/eating": "Yes" 

It works for the above aql where we give the attributes in the select statement
o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value as Condition, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value as Result


This aql works fine and returns only composition2
{ "q" : "SELECT e/ehr_id/value as ehrid, c/uid/value as compid, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value as Condition, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value as Result FROM ehr e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS (observation o[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]) WHERE o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value = 'Depression' and o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value = 'Yes' and c/archetype_details/template_id/value='sample_questionnaire.en.v0'" }

But if we remove the attributes from select, this returns the wrong results i.e it returns both the compositions.
{ "q" : "SELECT e/ehr_id/value as ehrid, c/uid/value as compid FROM ehr e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS (observation o[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]) WHERE o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value = 'Depression' and o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value = 'Yes' and c/archetype_details/template_id/value='sample_questionnaire.en.v0'" }

**Comment by vladislavploaia** [comment] 2023-01-19 13:50
Hello @rtchaya ,
Thank you for details.
Bug reported in our internal JIRA, to track the case described in your comment: https://jira.vitagroup.ag/browse/CDR-718
Will let you know if there are any updates on it.

CC: @vidi42

**Comment by rtchaya** [comment] 2023-01-20 15:17
Ok. Thanks

**Comment by stefanspiska** [comment] 2024-04-09 09:27
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0

**Closed by stefanspiska** 2024-04-09 09:27 UTC
Labels: bug
