### ISSUE TITLE
AQL - Different row results with the same data

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#718] opened 2022-01-04 07:03 UTC
## Configuration information

```
        ehrbase_version: '0.18.3',
        openehr_sdk_version: '1.7.0-SNAPSHOT',
        archie_version: '1.0.4',
        jvm_version: 'Oracle Corporation 11.0.13+8',
        os_version: 'Linux aarch64 5.10.76-linuxkit',
        postgres_version: 'PostgreSQL 13.4 (Debian 13.4-4.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit'
```

## Steps to reproduce ## 

Upload template: 
[Opd.opt.txt](https://github.com/ehrbase/ehrbase/files/7805819/Opd.opt.txt)

Upload composition:
```json
{
    "opd_temp.v1/category|code": "433",
    "opd_temp.v1/category|value": "event",
    "opd_temp.v1/category|terminology": "openehr",
    "opd_temp.v1/context/start_time": "2022-01-03T10:25:33.287Z",
    "opd_temp.v1/context/setting|code": "238",
    "opd_temp.v1/context/setting|value": "other care",
    "opd_temp.v1/context/setting|terminology": "openehr",
    "opd_temp.v1/clinical_background/covid_19_admission/hospital_admission_status|code": "at0005",
    "opd_temp.v1/clinical_background/covid_19_admission/hospital_admission_status|value": "UNKNOWN",
    "opd_temp.v1/clinical_background/covid_19_admission/hospital_admission_status|terminology": "local",
    "opd_temp.v1/clinical_background/covid_19_admission/date_first_admitted": "2021-11-22T15:54",
    "opd_temp.v1/clinical_background/covid_19_admission/language|code": "en",
    "opd_temp.v1/clinical_background/covid_19_admission/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/covid_19_admission/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/covid_19_admission/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/any_event:0/screening_purpose": "None",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/any_event:0/presence_of_any_symptoms_or_signs|code": "at0032",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/any_event:0/presence_of_any_symptoms_or_signs|value": "Absent",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/any_event:0/presence_of_any_symptoms_or_signs|terminology": "local",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/any_event:0/specific_symptom_sign:0/symptom_or_sign_name": "None",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/any_event:0/time": "2022-01-03T10:25:33.287Z",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/language|code": "en",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/symptom_sign_screening_questionnaire/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/any_event:0/temperature|unit": "Cel",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/any_event:0/temperature|magnitude": 50,
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/any_event:0/time": "2022-01-03T10:25:33.287Z",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/location_of_measurement|code": "at0061",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/location_of_measurement|value": "Forehead",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/location_of_measurement|terminology": "local",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/language|code": "en",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/vital_signs/body_temperature/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/clinical_background/vital_signs/respiration/any_event:0/presence|code": "at0063",
    "opd_temp.v1/clinical_background/vital_signs/respiration/any_event:0/presence|value": "Present",
    "opd_temp.v1/clinical_background/vital_signs/respiration/any_event:0/presence|terminology": "local",
    "opd_temp.v1/clinical_background/vital_signs/respiration/any_event:0/rate|unit": "/min",
    "opd_temp.v1/clinical_background/vital_signs/respiration/any_event:0/rate|magnitude": 47,
    "opd_temp.v1/clinical_background/vital_signs/respiration/any_event:0/time": "2022-01-03T10:25:33.287Z",
    "opd_temp.v1/clinical_background/vital_signs/respiration/language|code": "en",
    "opd_temp.v1/clinical_background/vital_signs/respiration/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/vital_signs/respiration/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/vital_signs/respiration/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/any_event:0/spo|numerator": 54,
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/any_event:0/spo|denominator": 100,
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/any_event:0/spo|type": 2,
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/any_event:0/time": "2022-01-03T10:25:33.287Z",
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/language|code": "en",
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/vital_signs/pulse_oximetry/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/travel|code": "at0006",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/travel|value": "Yes",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/travel|terminology": "local",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/domestic_international|code": "at0029",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/domestic_international|value": "International travel",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/domestic_international|terminology": "local",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/any_event:0/time": "2022-01-03T10:25:33.288Z",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/language|code": "en",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/travel_screening_questionnaire/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/any_event:0/test_name": "Covid Test",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/any_event:0/overall_test_status_timestamp": "2021-12-28T15:55",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/any_event:0/conclusion": "Positive",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/any_event:0/test_diagnosis:0": "Covid is detected",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/any_event:0/time": "2022-01-03T10:25:33.288Z",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/language|code": "en",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/language|terminology": "ISO_639-1",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/encoding|code": "UTF-8",
    "opd_temp.v1/clinical_background/lab_testing/laboratory_test_result/encoding|terminology": "IANA_character-sets",
    "opd_temp.v1/language|code": "en",
    "opd_temp.v1/language|terminology": "ISO_639-1",
    "opd_temp.v1/territory|code": "IN",
    "opd_temp.v1/territory|terminology": "ISO_3166-1",
    "opd_temp.v1/composer|name": "Medblocks UI"
}
```

## Actual result ##

Executing AQL: 
```
SELECT 
        c/uid/value,
        o/archetype_node_id, 
        o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude
        FROM COMPOSITION c
        CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]
```

Gets result with 4 rows:
```JSON
{
      "q": "SELECT \n        c/uid/value,\n        o/archetype_node_id, \n        o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude\n        FROM COMPOSITION c\n        CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]",
      "columns": [
        {
          "path": "/uid/value",
          "name": "#0"
        },
        {
          "path": "/archetype_node_id",
          "name": "#1"
        },
        {
          "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude",
          "name": "#2"
        }
      ],
      "rows": [
        [
          "eaf62b8c-416e-415f-a168-ef4bfcc61dff::localhost::1",
          "openEHR-EHR-OBSERVATION.respiration.v2",
          47
        ],
        [
          "eaf62b8c-416e-415f-a168-ef4bfcc61dff::localhost::1",
          null,
          47
        ],
        [
          "eaf62b8c-416e-415f-a168-ef4bfcc61dff::localhost::1",
          "openEHR-EHR-OBSERVATION.respiration.v2",
          null
        ],
        [
          "eaf62b8c-416e-415f-a168-ef4bfcc61dff::localhost::1",
          null,
          null
        ]
      ]
    }
```

Executing AQL:
```
SELECT 
        c/uid/value,
        o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude 
        FROM COMPOSITION c
        CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]
```

Gets result with 2 rows:
```JSON
{
      "q": "SELECT \n        c/uid/value,\n        o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude \n        FROM COMPOSITION c\n        CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]",
      "columns": [
        {
          "path": "/uid/value",
          "name": "#0"
        },
        {
          "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude",
          "name": "#1"
        }
      ],
      "rows": [
        [
          "eaf62b8c-416e-415f-a168-ef4bfcc61dff::localhost::1",
          47
        ],
        [
          "eaf62b8c-416e-415f-a168-ef4bfcc61dff::localhost::1",
          null
        ]
      ]
    }
```

## Expected result (Acceptance Criteria) ##

There's only 1 instance of the `openEHR-EHR-OBSERVATION.respiration.v2` archetype in the composition with the respiratory rate of 47. So I expect that only 1 row should be returned in both AQLs.

In inconsistency between the 2 AQLs by just adding/removing another `o/archetype_node_id` to the SELECT is also worrying me.

Hopefully, this is not expected behavior? Or maybe there's a deeper explanation as to why AQL behaves like this?

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment] 2022-01-11 07:02
@sidharthramesh the issue is with your template structure as it has embedded sections with the same archetype node id, but differentiated by their name/value. Under the hood, AQL path resolution is based on meta data provided by the WebTemplate. This has been a design decision to guarantee good performance when dealing with large data sets. 

In your scenario, the contains clause indicates the path to the OBSERVATION, but only using the archetype node ids. Why not also using name/value? The reason is that these are variables only known at the time the composition is committed (as it may be supplied by the user, f.e. using SNOMED codes). Since this embedding of sections results in multiple paths and then cartesian product as you've observed.

Thus if you want to ensure that you get only one row, you should constrain the nodes, f.e.

```
{
  "q": "SELECT 
        c/uid/value,
        c/content[openEHR-EHR-SECTION.adhoc.v1,'Clinical Background']/items[openEHR-EHR-SECTION.adhoc.v1, 'Vital Signs']/items[openEHR-EHR-OBSERVATION.respiration.v2]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude
        FROM COMPOSITION c
        CONTAINS SECTION s [openEHR-EHR-SECTION.adhoc.v1]
        CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]
"
}
```

An other way, is simply to use WHERE filtering.

PS. `o/archetype_node_id` is resolved as a constant (e.g. not queried) since it is an invariant provided by the containment resolution.

**Comment by sidharthramesh** [comment] 2022-01-17 11:11
Okay got it @chevalleyc. Thank you!

However, this issue does not happen with these compositions with very similar data using the same template:

[1.txt](https://github.com/ehrbase/ehrbase/files/7881322/1.txt)
[2.txt](https://github.com/ehrbase/ehrbase/files/7881323/2.txt)
[3.txt](https://github.com/ehrbase/ehrbase/files/7881324/3.txt)

**Comment by chevalleyc** [comment] 2022-04-07 06:51
@sidharthramesh  Hi, I have posted a branch with multiple fixes and optimizations related to this issue. Could you pls check it out? The branch is https://github.com/ehrbase/ehrbase/tree/feature/sync/737_value_point_paths . Thanks!

**Comment by sidharthramesh** [comment] 2022-04-07 06:58
Hey @chevalleyc! Thank you! I’ll test it out this week and give feedback.

**Closed** 2022-11-24 13:02 UTC
Labels: bug

**Comment by vladislavploaia** [comment] 2022-11-28 14:52
Hello All,
Based on issue description, I tested with 2 queries:
- SELECT c/uid/value,o/archetype_node_id, o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude FROM COMPOSITION c CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]
![image](https://user-images.githubusercontent.com/100927963/204307708-d243aaf1-3581-4233-bc41-3bea730927dc.png)
- SELECT c/uid/value,o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude FROM COMPOSITION c CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.respiration.v2]
![image](https://user-images.githubusercontent.com/100927963/204307927-be453a0b-05d0-4d7b-ae64-de37e9a261cf.png)

Both cases are **passed**, as they are returning only one row.
CC: @stefanspiska , @vidi42
