### ISSUE TITLE
Validation error due to missing mandatory elements that exist in the composition

### ISSUE THREAD

**Issue by ricardofago** [ehrbase/ehrbase#24] opened 2019-10-28 19:22 UTC
I successfully created an EHR and committed some of the compositions that are included as test resources based on the default OPTs shipped with the code base, but after uploading my own OPT, and trying to commit a valid composition there are some unexpected validation errors due to missing mandatory elements. I've attached the [composition.xml](https://gist.githubusercontent.com/ricardofago/7446ea8f8611add03faa14afe35603d1/raw/8d06a2cc66ae7530fbcaa0c7cde501fced7d8f82/composition.xml) and [OPT](https://gist.githubusercontent.com/ricardofago/7446ea8f8611add03faa14afe35603d1/raw/8d06a2cc66ae7530fbcaa0c7cde501fced7d8f82/Registro%2520de%2520Atendimento%2520Cl%25C3%25ADnico%2520v1.opt) in my [Gist](https://gist.github.com/ricardofago/7446ea8f8611add03faa14afe35603d1). The returned errors are:

```
Internal Server Error: org.ehrbase.validation.constraints.wrappers.ValidationException: 
Validation error at /content[openEHR-EHR-SECTION.problem_list.v1]/items[openEHR-EHR-ACTION.procedure-HAOC.v1]/description[at0001]/items[at0060], Mandatory element missing, expected:[1..1]
Validation error at /content[openEHR-EHR-SECTION.problem_list.v1]/items[openEHR-EHR-ACTION.procedure-HAOC.v1]/description[at0001]/items[at0.74], Mandatory element missing, expected:[1..1]
Validation error at /content[openEHR-EHR-SECTION.problem_list.v1]/items[openEHR-EHR-ACTION.procedure-HAOC.v1]/description[at0001]/items[at0.70], Mandatory element missing, expected:[1..1]
Validation error at /content[openEHR-EHR-SECTION.problem_list.v1]/items[openEHR-EHR-ACTION.procedure-HAOC.v1]/description[at0001]/items[at0002.1], Mandatory element missing, expected:[1..1]
Validation error at /content[openEHR-EHR-SECTION.problem_list.v1]/items[openEHR-EHR-EVALUATION.problem_diagnosis-ms_br.v1]/data[at0001]/items[at0002.1], Mandatory element missing, expected:[1..1]
```

But by inspecting the composition we can see that the elements are there. I tried increasing the log verbosity but didn't get much help from the console. I could trace that the composition with the data points above was processed, but I suspect the problem is that the OPT defines multiple ``/content[openEHR-EHR-SECTION.problem_list.v1]`` siblings (with the same ``archetype_node_id``), but the template refine their contents differently by renaming and including/restricting different children in their slots, so EHRbase might be validating a content block against the wrong (possibly first) definition.

**Comment by ricardofago** [comment] 2019-10-28 19:29
I also contacted @wolandscat about the proper way to discern different siblings with the same ``archetype_node_id``. In the OPT from this scenario, the siblings are optional so relying on index/order might not be reasonable. Ocean's Template Designer (and I think I've also seen EtherCIS do something similar in the past) use the name attribute as a predicate to refine the path expression, but this may create issues due to relying on localized text, breaking stuff for instances of archetypes with multiple translations/different languages. Maybe archetyped term definitions could be used? What do you think?

**Comment by chevalleyc** [comment] 2019-11-27 03:55
Hi Ricardo, could you please post your composition xml and OPT? The provided links seem broken. Many thanks

**Comment by ricardofago** [comment] 2019-11-27 18:09
Hi Christian, sorry about that, for some reason the Gist links changed. I've edited them in the first post.
(https://gist.github.com/ricardofago/7446ea8f8611add03faa14afe35603d1)

**Comment by chevalleyc** [comment] 2019-12-09 08:00
Seems the issue is that in the composition, there are multiple 
```
 <content archetype_node_id="openEHR-EHR-SECTION.problem_list.v1" xsi:type="SECTION">
```
Causing the identification of node f.e. with path:

```
/content[openEHR-EHR-SECTION.problem_list.v1]/items[openEHR-EHR-ACTION.procedure-HAOC.v1]/description[at0001]/items[at0060]
```
to fail unless it is located at the top of the tree (in sequence). Thus a workaround is to avoid the above duplication by mean of template refactoring if it is possible until this issue is fixed (it is a low level issue AFAIK). Tx

**Comment by chevalleyc** [comment] 2019-12-16 09:24
@ricardofago I have pushed a fix related to the validation issue. However, there is another issue with sections sharing the same archetype node id, but with a different name. At the moment, the name is not properly propagated into the serialized json stored in the DB. As a result, the composition is not fully persisted in this particular scenario (NB. this issue only happens with SECTION AFAIK). One workaround is to use different section node ids or refactoring the template so structures are assigned to unique sections.

**Comment by chevalleyc** [comment] 2019-12-16 09:24
See https://github.com/ehrbase/ehrbase/tree/feature/24_validation_error_for_existing_mandatory_elements for details

**Comment by Geisterfalle** [comment] 2020-02-07 13:06
@chevalleyc @ricardofago My understanding is that the issue has been successfully resolved and I can close the issue. Is this correct?

**Comment by ricardofago** [comment] 2020-02-07 18:36
To be honest I got caught up in some other stuff and phased out so I haven't tested this recently, but from the latest/referenced activity I'm assuming the problem with generic SECTION instances with the same archetype_node_id but different names still remain... As arguable as it could be from a semantic perspective, I think it would still be a fairly common scenario in templates due to grouping/structuring blocks for data entry.
I'm not sure the issue is entirely resolved. @chevalleyc can elaborate better, or it might be more reasonable to close this and raise a more specific/tailored issue.

**Comment by chevalleyc** [comment] 2020-02-10 02:01
With the current code base (0.10.0), the above example composition example is now validated and stored properly including the SECTIONs with different names. I agree with @ricardofago , should this issue occurs please open a new CR.
NB. the validation now check DvCodedText value against localized terminology (here 'pt') please make sure that the value is actually localized as well (f.e. `evento` instead of `event`) etc.

**Closed by chevalleyc** 2020-02-10 02:01 UTC
