### ISSUE TITLE
Inconsistency between CKM/OPT and WebTemplate

### ISSUE THREAD

**Issue by richter122-goe** [ehrbase/ehrbase#765] opened 2022-03-01 13:44 UTC
## Configuration information

<ehrbase_version>0.20.0-SNAPSHOT</ehrbase_version>
<openehr_sdk_version>1.18.0-SNAPSHOT</openehr_sdk_version>
<archie_version>1.0.4</archie_version>
<jvm_version>Oracle Corporation 11.0.14.1+1</jvm_version>
<os_version>Linux amd64 5.4.0-90-generic</os_version>
<postgres_version>PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit</postgres_version>

## Steps to reproduce ## 

0. CKM shows a fixed terminology for CODED_TEXT-Field "Bezeichnung des Analyts" with Terminology [http://loinc.org] [results-laboratory-observations-uv-ips]
![image](https://user-images.githubusercontent.com/64580653/156177884-836fde34-8faf-4cf5-a0b3-c2d2bd7f051f.png)

1. Upload OPT to EHRBase -> [KDS_Laborbericht.opt.txt](https://github.com/ehrbase/ehrbase/files/8161854/KDS_Laborbericht.opt.txt)

2. Retrieve WebTemplate or store a composition related to this Template

## Actual result ##

After retrieving the WebTemplate from EHRBase the WebTemplate shows '//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips' as terminology-value for "Bezeichnung des Analyts"

```
"id": "bezeichnung_des_analyts",
"name": "Bezeichnung des Analyts",
"localizedName": "Bezeichnung des Analyts",
"rmType": "DV_CODED_TEXT",
"min": 1,
"max": 1,
"localizedNames": {
    "de": "Bezeichnung des Analyts"
},
"localizedDescriptions": {
    "de": "Der Name des untersuchten Analyts."
},
"aqlPath": "/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1,'Laborbefund']/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1,'Pro Laboranalyt']/items[at0024]/value",
"inputs": [
    {
        "suffix": "code",
        "type": "TEXT",
        "terminology": "//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips"
    },
    {
        "suffix": "value",
        "type": "TEXT",
        "terminology": "//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips"
    }
]
```

In case a composition is created the EHRBase takes any (text-)value for the field "Bezeichnung des Analyts". When the composition is queried it shows that "//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips" is stored as terminology for "Bezeichnung des Analyts".

## Expected result (Acceptance Criteria) ##

- Consistency between OPT?/CKM and WebTemplate.
- Either give an error message for trying to create a composition with wrong terminology on that field or store the terminology-string that was given in the composition

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vmueller-vg** [comment] 2022-03-21 15:52
Regarding the consistency between CKM/OPT and the Webtemplate: 
The OPT you provided contains `<referenceSetUri>terminology://fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips</referenceSetUri>` meaning the given part resulting Webtemplate is consistent with the OPT. 

Regarding the proper validation i will look into it.

**Comment by vmueller-vg** [comment] 2022-03-22 17:43
to validate non openEHR terminologies the ehrbase instance has to be configured to use an external terminology server and external validation has to be enabled explicitly. 
If you have done so and the validation still does not work, please create a new issue with an example template, payload, actual outcome and expected outcome.

I will close this, since ehrbase works as intended and the CKM and how it displays terminology bindings is not part of this project/repository.

**Closed by vmueller-vg** 2022-03-22 17:43 UTC
Labels: bug

**Comment by richter122-goe** [comment] 2022-03-22 18:02
Hello, i was just working on providing an example and a clearer explanation.

- I send a resource with a terminology set to "http://loinc.org".
- It is created with HTTP 201.
- I can´t find it via AQL using WHERE terminology = 'http://loinc.org' because this is not the value that was stored.

This was unexpected for me. Yes, there is no validation in place 
but with a 201 Response i didn´t expect the server to change the values within the composition.

Resource send to the server: 
(Please note: "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|terminology": "http://loinc.org",)
```
{
    "laborbericht/context/bericht_id": "111",
    "laborbericht/context/status": "unknown",
    "laborbericht/context/fallidentifikation/fall-kennung": "top_secret2",
    "laborbericht/context/start_time": "2020-01-01T00:00:00",
    "laborbericht/laborbefund/labortest-kategorie|value": "laboratory",
    "laborbericht/laborbefund/labortest-kategorie|code": "26436-6",
    "laborbericht/laborbefund/labortest-kategorie|terminology": "LOINC",
    "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|value": "Kreatinin",
    "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|code": "2160-0",
    "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|terminology": "http://loinc.org",
    "laborbericht/laborbefund/pro_laboranalyt:0/messwert:0/quantity_value|magnitude": "151.3",
    "laborbericht/laborbefund/pro_laboranalyt:0/messwert:0/quantity_value|unit": "mg/dL",
    "laborbericht/laborbefund/pro_laboranalyt:0/ergebnis-status|value": "Vorläufig",
    "laborbericht/laborbefund/pro_laboranalyt:0/ergebnis-status|code": "at0017",
    "laborbericht/laborbefund/pro_laboranalyt:0/ergebnis-status|terminology": "local",
    "laborbericht/laborbefund/time": "2020-01-01T00:00:00",
    "laborbericht/laborbefund/details_der_testanforderung/identifikation_der_laboranforderung/text_value": "top_secret2",
    "laborbericht/laborbefund/subject|name": "top_secret",
    "laborbericht/laborbefund/language|code": "de",
    "laborbericht/laborbefund/language|terminology": "ISO_639-1",
    "laborbericht/laborbefund/encoding|code": "UTF-8",
    "laborbericht/laborbefund/encoding|terminology": "IANA_character-sets",
    "laborbericht/composer|name": "j_richter",
    "laborbericht/language|code": "de",
    "laborbericht/language|terminology": "ISO_639-1",
    "laborbericht/territory|code": "DE",
    "laborbericht/territory|terminology": "ISO_3166-1"
}
```

Resource queried from the server by Composition ID:
(Please note: "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|terminology": "//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips")
```
{
    "meta": {
        "href": {
            "url": "http://9df06ddc6241:8080/ehrbase/rest/ecis/v1/composition/00db3ca9-d381-416d-b4cb-0df8f65c0647"
        }
    },
    "action": "RETRIEVE",
    "composition": {
        "laborbericht/category|terminology": "openehr",
        "laborbericht/category|code": "433",
        "laborbericht/category|value": "event",
        "laborbericht/context/bericht_id": "111",
        "laborbericht/context/status": "unknown",
        "laborbericht/context/fallidentifikation/fall-kennung": "top_secret2",
        "laborbericht/context/start_time": "2020-01-01T00:00:00",
        "laborbericht/context/setting|code": "238",
        "laborbericht/context/setting|terminology": "openehr",
        "laborbericht/context/setting|value": "other care",
        "laborbericht/laborbefund/labortest-kategorie|value": "laboratory",
        "laborbericht/laborbefund/labortest-kategorie|terminology": "LOINC",
        "laborbericht/laborbefund/labortest-kategorie|code": "26436-6",
        "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|terminology": "//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips",
        "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|code": "2160-0",
        "laborbericht/laborbefund/pro_laboranalyt:0/bezeichnung_des_analyts|value": "Kreatinin",
        "laborbericht/laborbefund/pro_laboranalyt:0/messwert:0/quantity_value|magnitude": 152.3,
        "laborbericht/laborbefund/pro_laboranalyt:0/messwert:0/quantity_value|unit": "mg/dL",
        "laborbericht/laborbefund/pro_laboranalyt:0/ergebnis-status|code": "at0017",
        "laborbericht/laborbefund/pro_laboranalyt:0/ergebnis-status|value": "Vorläufig",
        "laborbericht/laborbefund/pro_laboranalyt:0/ergebnis-status|terminology": "local",
        "laborbericht/laborbefund/time": "2020-01-01T00:00:00",
        "laborbericht/laborbefund/details_der_testanforderung/identifikation_der_laboranforderung/text_value": "top_secret2",
        "laborbericht/laborbefund/language|code": "de",
        "laborbericht/laborbefund/language|terminology": "ISO_639-1",
        "laborbericht/laborbefund/encoding|code": "UTF-8",
        "laborbericht/laborbefund/encoding|terminology": "IANA_character-sets",
        "laborbericht/laborbefund/subject|name": "top_secret",
        "laborbericht/language|code": "de",
        "laborbericht/language|terminology": "ISO_639-1",
        "laborbericht/territory|code": "DE",
        "laborbericht/territory|terminology": "ISO_3166-1",
        "laborbericht/composer|name": "j_richter",
        "laborbericht/_uid": "00db3ca9-d381-416d-b4cb-0df8f65c0647::local.ehrbase.org::1"
    },
    "format": "FLAT",
    "templateId": "KDS_Laborbericht",
    "ehrId": "1410d025-5d3c-4be1-89da-2a81a90d35b3",
    "compositionUid": "00db3ca9-d381-416d-b4cb-0df8f65c0647"
}
```

**Comment by vmueller-vg** [comment] 2022-03-22 19:15
I double checked and stuff that is defined as fixed (like a bound terminology-id) in the webtemplate takes precedence over the user input. So it is indeed intentional.
