### ISSUE TITLE
Fail to create EHR when running in Docker - Could not getNewFolderAccessInstance / Cannot translate a null SQLException

### ISSUE THREAD

**Issue by wlad** [ehrbase/ehrbase#460] opened 2021-03-11 11:57 UTC
## Configuration information

 ```
 "ehrbase_version": "0.15.0",
 "openehr_sdk_version": "f7a75b2",
 "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
 "jvm_version": "Oracle Corporation 11.0.10+9",
 "os_version": "Linux amd64 5.10.0-kali3-amd64",
 "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
```

## Steps to reproduce ## 

1. clone [fhir-bridge](https://github.com/ehrbase/fhir-bridge) repo
2. cd docker
3. docker-compose -f docker-compose-light.yml up
4. create an EHR
```
POST {{ehrbase_url}}/ehr HTTP/1.1
content-type: application/json
Prefer: return=representation
Authorization: Basic bXl1c2VyOm15UGFzc3dvcmQ0MzI=

{
  "_type": "EHR_STATUS",
  "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
  "name": {
    "value": "EHR Status"
  },
  "subject": {
    "external_ref": {
      "id": {
        "_type": "GENERIC_ID",
        "value": "{{uuid}}",
        "scheme": "id_scheme"
      },
      "namespace": "foo_{{subject_namespace}}",
      "type": "PERSON"
    }
  },
  "is_modifiable": true,
  "is_queryable": true
}
```

## Actual result ##

```
{
  "error": "Could not getNewFolderAccessInstance settings:local.ehrbase.org Exception:java.lang.IllegalArgumentException: Cannot translate a null SQLException",
  "status": "Bad Request"
}
```

## Expected result (Acceptance Criteria) ##

201 - EHR created

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by wlad** [comment] 2021-03-11 12:16
:warning:  NOTE: issue must be related to the docker image. Steps above are not reproducible when erhrbase is started natively via `java -jar ...` (without Docker).

**Comment by sidharthramesh** [comment] 2022-07-26 12:15
This issue is present, but I'm not able to reproduce it properly. It is occurring on some deployments with ehrbase/ehrbase:0.21.1 as well as ehrbase/ehrbase:nex but not others.

Truly bizarre.

**Comment by sidharthramesh** [comment] 2022-07-26 12:48
Okay never mind. It was some issue with not properly running the initial SQL migration. No issue with EHRbase.

**Comment by vladislavploaia** [comment] 2023-02-10 13:11
Hello @wlad ,
Referring to previous comment, I am closing current ticket.
CC: @vidi42

**Closed by vladislavploaia** 2023-02-10 13:11 UTC
Labels: bug, docker
