### ISSUE TITLE
Missing required attribute symbol in DV_ORDINAL class

### ISSUE THREAD

**Issue by gregorberger** [ehrbase/ehrbase#874] opened 2022-05-23 09:31 UTC
## Steps to reproduce ## 

`robot -t "Main flow create new event COMPOSITION FLAT" robot/COMPOSITION_TESTS/CREATE_COMPOSITION/"B.6.a_main_flow_create_new_event_COMPOSITION".robot`

## Actual result ##

```

POST Response : url=/rest/openehr/v1/ehr/a061cf43-19ed-4c7f-b006-5f6cef1e3110/composition?format=FLAT&ehrId=a061cf43-19ed-4c7f-b006-5f6cef1e3110&templateId=nested.en.v1  
status=400, reason=Bad Request
body={"message":"Composition validation failed (there are missing or invalid values).","validation_errors":["Required property /content[openEHR-EHR-SECTION.nested.v1,'Nested']/items[openEHR-EHR-INSTRUCTION.nested.v1,'Nested']/activities[at0001,'Current Activity']/description[openEHR-EHR-ITEM_TREE.nested.v1,'Nested']/items[at0002,'ordinal']/value/symbol missing"]} 
```

## Expected result (Acceptance Criteria) ##

201 Status code

When running above test on our custom system, we get the 400 status code, because of validation error.
In file `nested.en.v1__full.xml.flat.json` attribute symbol is missing in DV_ORDINAL class.
As you can see in specification: https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_ordinal_class
symbol is required(1 .. 1) in DV_ORDINAL.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment] 2022-05-23 12:48
Hello @gregorberger,
I analyzed your issue and was not able to reproduce it.
In addition, I see in file **nested.en.v1__full.xml.flat.json**, the following values were provided:
![image](https://user-images.githubusercontent.com/100927963/169822454-c2b0bb41-7d57-4c0a-8ff1-4f691297e187.png)
PFA passed report from test case execution.
[log_success.zip](https://github.com/ehrbase/ehrbase/files/8754606/log_success.zip)

**Comment by vladislavploaia** [comment] 2022-07-11 12:11
Hello @gregorberger,
Still cannot reproduce this issue in EHRBase version **0.22.0**.
![image](https://user-images.githubusercontent.com/100927963/178260220-7f8e800a-7416-4d38-8c90-c159283919ce.png)
Based on our internal approach, all issues should be tested on latest version of EHRBase. If the corresponding issue is not reproducible, we ask for feedback (additional info, test data...) from the creator, to, eventually, reproduce the issue if possible. If this stage is consumed (still cannot reproduce), we are closing Github issue with label won't fix.

So, if you can help me with some additional info/live testing on our EHRBase version, anything which will reproduce the issue, I am happy to do it so, otherwise, ticket will be closed.
CC: @stefanspiska

**Comment by vladislavploaia** [comment] 2022-07-21 07:11
Issue closed, as no further actions were supposed to be done.
Checked on EHRBase version **0.22.0**, as mentioned in previous comment. Not able to reproduce it.

**Closed by vladislavploaia** 2022-07-21 07:11 UTC
Labels: feedback
