### ISSUE TITLE
Inconsistency in creating or updating 2 EHRs to have the same subject Id

### ISSUE THREAD

**Issue by robert-hunter-nes** [ehrbase/ehrbase#932] opened 2022-07-06 14:10 UTC
## Configuration information

- EHRbase version: 0.21.1
- openEHR_SDK version: 1.19.0
- Archie version: 2.0.1
- PostgreSQL version: PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
- Java Runtime version: Oracle Corporation 11.0.15+10
- Operating System version: Linux amd64 5.10.47-linuxkit

## Steps to reproduce ## 

1. Create an EHR with identifier 0000000001
    ```
    curl --location --request POST 'http://localhost:38084/ehrbase/rest/openehr/v1/ehr' \
    --header 'Content-Type: application/json' \
    --header 'Prefer: return=representation' \
    --header 'Authorization: Basic <removed>' \
    --data-raw '{
       "_type": "EHR_STATUS",
       "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
       "name": {
         "value": "EHR Status"
       },
       "subject": {
         "_type": "PARTY_SELF",
         "external_ref": {
           "type": "PERSON",
           "namespace": "my-namespace",
           "id": {
             "_type": "GENERIC_ID",
             "value": "0000000001",
             "scheme": "my-scheme"
           }
         }
       },
       "is_modifiable": true,
       "is_queryable": true
    }'
    ```
2. Try to create another one with the same identifier and get a 409 Conflict response
    ```
    {"error":"Conflict","message":"Specified party has already an EHR set (partyId=25dde7db-a689-492f-a53f-d174144c6563)"}
    ```

If I try to approach this a different way and rather than try and create a new one with the same identifier, but create one with a different identifier and then update it to match the first one it will work, so continuing form the above steps

3.  Create an EHR with a different identifier 0000000002
    ```
    curl --location --request POST 'http://localhost:38084/ehrbase/rest/openehr/v1/ehr' \
    --header 'Content-Type: application/json' \
    --header 'Prefer: return=representation' \
    --header 'Authorization: Basic <removed>' \
    --data-raw '{
       "_type": "EHR_STATUS",
       "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
       "name": {
         "value": "EHR Status"
       },
       "subject": {
         "_type": "PARTY_SELF",
         "external_ref": {
           "type": "PERSON",
           "namespace": "my-namespace",
           "id": {
             "_type": "GENERIC_ID",
             "value": "0000000002",
             "scheme": "my-scheme"
           }
         }
       },
       "is_modifiable": true,
       "is_queryable": true
    }'
    ```
4. Update it to be the same as the original identifier 0000000001
    ```
    curl --location --request PUT 'http://localhost:38084/ehrbase/rest/openehr/v1/ehr/9e4d6c09-80f4-48c8-a784-725a03055e66/ehr_status' \
    --header 'Content-Type: application/json' \
    --header 'If-Match: 0b2f9cfb-9df2-4fea-bf71-9c7609e49cd4::local.ehrbase.org::1' \
    --header 'Authorization: Basic <removed>' \
    --data-raw '{
      "_type": "EHR_STATUS",
      "name": {
        "_type": "DV_TEXT",
        "value": "EHR Status"
      },
      "subject": {
        "external_ref": {
          "_type": "PARTY_REF",
          "namespace": "my-namespace",
          "type": "PERSON",
          "id": {
            "_type": "GENERIC_ID",
            "value": "0000000001",
            "scheme": "my-scheme"
          }
        }
      },
      "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
      "uid": {
        "_type": "OBJECT_VERSION_ID",
        "value": "0b2f9cfb-9df2-4fea-bf71-9c7609e49cd4::local.ehrbase.org::1"
      },
      "is_modifiable": true,
      "is_queryable": true
    }'
    ```

## Actual result ##

I was unable initially to create 2 EHRs with the same subject Id when trying to create them the application stopped me, but it then let me update a different EHRs subject Id to match that of the original one, and results in me being unable to look up an EHR by subject Id. Evidenced below

We can see here that I have 2 different EHR Ids with the same subject Id
```
Request
---
curl --location --request POST 'http://localhost:38084/ehrbase/rest/openehr/v1/query/aql' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Basic <removed> \
--data-raw '{
  "q": "SELECT e/ehr_id/value as ehrId, e/ehr_status/subject/external_ref/id/value as chi FROM EHR e ORDER BY e/ehr_status/subject/external_ref/id/value DESC"
}'

Result
---
{
  "q": "SELECT e/ehr_id/value as ehrId, e/ehr_status/subject/external_ref/id/value as chi FROM EHR e ORDER BY e/ehr_status/subject/external_ref/id/value DESC",
  "columns": [
    {
      "path": "/ehr_id/value",
      "name": "ehrId"
    },
    {
      "path": "/ehr_status/subject/external_ref/id/value",
      "name": "chi"
    }
  ],
  "rows": [
    [
      "4dea16f8-7506-405f-a5fd-af032312fc6e",
      "0000000001"
    ],
    [
      "9e4d6c09-80f4-48c8-a784-725a03055e66",
      "0000000001"
    ]
  ]
}
```

But I can no longer fetch the EHR by subject Id (which I guess makes sense)
```
Request
---
curl --location --request GET 'http://localhost:38084/ehrbase/rest/openehr/v1/ehr?subject_id=0000000001&subject_namespace=my-namespace' \
--header 'Authorization: Basic <removed>' \
--data-raw ''

Response
---
{
  "error": "Bad Request",
  "message": "Could not retrieve  EHR for party:3801b7ef-604a-41a9-b309-6b5a48ea9096 exception:java.lang.IllegalArgumentException: Cannot translate a null SQLException"
}
```

## Expected result (Acceptance Criteria) ##

I think I would probably expect it to be consistent and if it stops me from creating 2 EHRs with the same subject Id, then it probably shouldn't let me update an EHR with a subject Id already assigned to an existing EHR, or vice-versa.

tbh I'm not clear what the expected behaviour is supposed to be as the spec on [EHR Creation](https://specifications.openehr.org/releases/RM/latest/ehr.html#_ehr_creation) says that you can have multiple EHRs for a single patient in a distributed system where copying has occurred (there may be an assumption there that the patient would have different subject Ids on each EHR, but it's not stated), but I could easily be misunderstanding that.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment] 2022-07-08 09:33
Hello @robert-hunter-nes,
Such detailed description on current ticket. I appreciate it!

I checked the cases above and seems that the issue is not reproducible.
I was not able to update the first and second ehr, via PUT request (changing only the Subject Id).
There are two cases covered by me:
1. Update EHR using one of the existing EHR Id, which gave me this result:
![image](https://user-images.githubusercontent.com/100927963/177962671-18c004de-25a0-4849-9e4e-884295db0609.png)
2. Update EHR using a randomly generated EHR Id:
![image](https://user-images.githubusercontent.com/100927963/177962863-e5e06b82-1e59-4acf-909a-55ba783e0027.png)
As you can see, in both cases, it did not allow me to update an existing EHR.
Tested on EHRBase version **0.22.0**
In case you have any questions/additional details please let me know, otherwise I will close this ticket.

Thank you!

**Comment by robert-hunter-nes** [comment] 2022-07-08 10:56
Hi @vladislavploaia, thanks for your reply.

When I seen your message it crossed my mind that 0.21.1 might be a little out of date, so I pulled your `next` image hoping to confirm that it was not an issue, but I'm still able to reproduce it.

This time I have used the `next` image that was last updated 2 days ago at time of writing which is version
```
{
  "ehrbase_version": "0.22.0-SNAPSHOT",
  "openehr_sdk_version": "1.20.0-SNAPSHOT",
  "archie_version": "2.0.1",
  "jvm_version": "Oracle Corporation 11.0.15+10",
  "os_version": "Linux amd64 5.10.104-linuxkit",
  "postgres_version": "PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit"
}
```

The steps I followed were
1. Create a new EHR with identifier set to `0000000001`
2. Create a new EHR with identifier set to `0000000002`
3. Use the ehr_status endpoint to update the second EHR identifier to match the first one, I needed to set EHR id in the URI, and the EHR status id in the body and if-match header 

At this point I was able to query and see I had 2 EHRs with the same identifier value
![Screenshot 2022-07-08 at 11 46 15](https://user-images.githubusercontent.com/50167182/177978516-556568ba-c955-427b-ad6d-0a289290384a.png)

I'm able to reproduce it fairly consistently. I may be misunderstanding identifiers names, but it's specifically the EHR subjects identifier value that I'm updating, so I'm using the EHR and EHR status Ids that were generated by EHRbase when I created the EHR.

Not sure if that helps you reproduce it?

**Comment by vladislavploaia** [comment] 2022-07-08 13:13
@robert-hunter-nes - bug reported in JIRA, for tracking purposes.
https://jira.vitagroup.ag/browse/CDR-458
I am able to reproduce it as well:
![image](https://user-images.githubusercontent.com/100927963/177998572-f720725a-d51e-4ea5-8e69-baab1d3ecb78.png)

**Comment by vladislavploaia** [comment] 2023-08-10 13:54
Ticket closed as internal ticket 458, is closed as well.
Issue fixed.
CC: @vidi42

**Closed by vladislavploaia** 2023-08-10 13:54 UTC
Labels: bug
